### ISSUE TITLE
Problèmes après installation

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoPaysages#52]
L'installation de la v1.0.0-rc.3.1 a bien fonctionné.

Néanmoins je rencontre ensuite des problèmes. 

Quand j'essaie d'accéder à l'application, j'ai une Internal error. 
Le fichier ``/var/log/oppv_vanoise/oppv_vanoise.err.log`` indique : 

```
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-31 10:05:55,595] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/geonatureadmin/geopaysages/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/geonatureadmin/geopaysages/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_requ$
    rv = self.handle_user_exception(e)
  File "/home/geonatureadmin/geopaysages/venv/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_$
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/geonatureadmin/geopaysages/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_except$
    reraise(exc_type, exc_value, tb)
  File "/home/geonatureadmin/geopaysages/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/geonatureadmin/geopaysages/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_requ$
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geopaysages/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/geonatureadmin/geopaysages/backend/routes.py", line 45, in home
    sites.append(sites[x])
IndexError: list index out of range
```

Certainement car je n'ai encore aucun site dans la BDD. Mais ce cas devrait être géré ?
Ou fournir un site exemple lors de l'installation de la BDD ?

Du coup j'ai essayé d'accéder au Backoffice pour créer un site. J'y accède bien, mais impossible de me connecter, j'obtiens une erreur 405 avec l'utilisateur admin / admin

```
POST http://51.77.158.17/app_admin/auth/login 405 (Not Allowed)
```

**Comment by HamoudaAmine** [comment]
- J' ai rajouté un exemple de site dans BDD.
- L'erreur 405 de connexion est à cause de l'id_application qui ne correspond pas à celui dans BDD. 
- Il faut mettre id_application = 1 ce qui correspond à l'id_application que j'ai mis par défaut pour l'utilisateur admin (démo).

**Comment by Chrispnv** [comment]
L'installation s'est à priori bien passée.
Dans le navigateur, j'ai 502 Bad Gateway. J'ai vu avec Amine qui regarde de son coté.
Dans /etc/nginx/conf.d/oppv_vanoise.conf le server_name est l'IP de ma machine virtuelle.
@camillemonchicourt et @TheoLechemia quelle valeur vous avez mis pour server_name ?
Merci.

**Comment by Chrispnv** [comment]
Pb résolu pour le 502 Bad Gateway.
J'ai enlevé cache et cookies sur le navigateur.
@HamoudaAmine tu peux arrêter de chercher. On teste plus en avant avec Patrick et on te tient au courant.
Merci.

**Comment by camillemonchicourt** [comment]
Installation OK pour nous aussi sur la v1.0.0-rc.3.7
